---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/investigators":
    post:
      summary: Creates an investigator
      tags:
      - Investigators
      parameters: []
      responses:
        '201':
          description: investigator created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                photo:
                  type: string
                description:
                  type: string
                fee:
                  type: number
                rating:
                  type: number
              required:
              - name
              - photo
              - description
              - fee
              - rating
  "/v1/investigators/{id}":
    get:
      summary: Retrieves an investigator
      tags:
      - Investigators
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: id found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  photo:
                    type: string
                  description:
                    type: string
                  fee:
                    type: float
                  rating:
                    type: number
                required:
                - name
                - photo
                - description
                - fee
                - rating
        '404':
          description: investigator not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
